### ISSUE TITLE
Full C# API?? 

### ISSUE THREAD

**Issue by LudoTexx** [stereolabs/zed-csharp-api#1]
Hello,

So... i just found this page while checking Zed github randomly...

This is true, a full C# API for the zed cam??? Streaming, detection, etc... without C++??

Please tell me is true..., did you have date for release ???? Is this stable actually??

That very awesome guys, thank you !!!!!!

**Comment by obraun-sl** [comment]
Hi,
This is a wrapper around C++ API. Therefore it calls inside the C++ functions but all your code will be in C#. 
It contains all the functions of the ZED SDK 3.1. 
This is stable and the first version. Just clone this repository.

**Comment by LudoTexx** [comment]
Did you have any idea about a date for streaming Function ?

**Comment by obraun-sl** [comment]
It's already available : 
On Sender , use EnableStreaming() function
On Reciever, use initParameters.ipStream and initParameters.portStream

**Comment by PrivHateVoid** [comment]
That great thanks.

I can run the Hello ZED sample, that ok.

But i already have a big, big project in C# WPF, did you know a way to add directly a zed.dll into my project reference and just use the DLL like i do usually (GPIO card, joystick, etc..) without cmake, who creating project with ZERO_CHECK, ALL_BUILD etc... ??

**Comment by LudoTexx** [comment]
Thank you, Can i receive stream from c++ sender to C# receiver? I try but that doesnt work, but receiver work in c++.

Edit : work !

need to add :
init_params.inputType = INPUT_TYPE.INPUT_TYPE_STREAM

👍
