### ISSUE TITLE
Cann't build the image_Capture for unable to find the sl_zed_interface.dll

### ISSUE THREAD

**Issue by Lancename** [stereolabs/zed-csharp-api#10]
it is like that the sl_zed_interface.dll is created in C , and cann't import in C#.   can  any one  solve it ? thank you very much

**Comment by obraun-sl** [comment]
sl_zed_interface.dll is a C wrapper library of the C++ SDK. It must be in C so that C# can import the function (through dllimport).
Please follow the instructions on the ReadMe to build the C# Net wrapper that will install sl_zed_interface in the appropriate location.

**Comment by Lancename** [comment]
> sl_zed_interface.dll is a C wrapper library of the C++ SDK. It must be in C so that C# can import the function (through dllimport).
> Please follow the instructions on the ReadMe to build the C# Net wrapper that will install sl_zed_interface in the appropriate location.

thanks for quick reply.     i build the  stereolabs.zed,and  there are the sl_zed_interface.dll and stereolabs.zed.dll in the  "bin" ,but however when i build the tutorials, it doesn't work well,  and show the error that cann't import the sl_zed_omyerface.dll  because it is a C wrapper. 
I am sure that there is no problem before this, so  should i write the code to import this c  wrapper by myself(using dllimport) ,or this project already comes with it ?

**Comment by Lancename** [comment]
> sl_zed_interface.dll is a C wrapper library of the C++ SDK. It must be in C so that C# can import the function (through dllimport).
> Please follow the instructions on the ReadMe to build the C# Net wrapper that will install sl_zed_interface in the appropriate location.

![image](https://user-images.githubusercontent.com/24515772/91175802-ec1deb00-e713-11ea-900d-25d5fa885c3e.png)

**Comment by Lancename** [comment]
> > sl_zed_interface.dll is a C wrapper library of the C++ SDK. It must be in C so that C# can import the function (through dllimport).
> > Please follow the instructions on the ReadMe to build the C# Net wrapper that will install sl_zed_interface in the appropriate location.
> 
> thanks for quick reply. i build the stereolabs.zed,and there are the sl_zed_interface.dll and stereolabs.zed.dll in the "bin" ,but however when i build the tutorials, it doesn't work well, and show the error that cann't import the sl_zed_omyerface.dll because it is a C wrapper.
> I am sure that there is no problem before this, so should i write the code to import this c wrapper by myself(using dllimport) ,or this project already comes with it ?

![image](https://user-images.githubusercontent.com/24515772/91175951-27201e80-e714-11ea-97d1-fec0b5ec52c6.png)

**Comment by Lancename** [comment]
> sl_zed_interface.dll is a C wrapper library of the C++ SDK. It must be in C so that C# can import the function (through dllimport).
> Please follow the instructions on the ReadMe to build the C# Net wrapper that will install sl_zed_interface in the appropriate location.

thank you for your reply. I get it .   I remove the sl_zed_interface  in the picture and replace it using stereolabs.zed.  and it work well.  
![image](https://user-images.githubusercontent.com/24515772/91177345-28eae180-e716-11ea-8848-62022e8631e0.png)
