### ISSUE TITLE
Reporting Error When using ZEDFU

### ISSUE THREAD

**Issue by alphonse-lin** [stereolabs/zed-csharp-api#18]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

![image](https://user-images.githubusercontent.com/38575020/156887500-4b2af63d-a9e8-4b36-9925-9a9c3cbc6b3d.png)

Sorry, I don't know where I can raise an issue about ZEDFU, so I just post here.

It keeps reporting this error when I am using ZEDFu.

### Steps to Reproduce

1. Open ZEDFu
2. Click Reset
3. Click Start, and Stop, it would pop the error
...

### Expected Result

I supposed ZEDFu could export this model into obj model

### Actual Result

![image](https://user-images.githubusercontent.com/38575020/156887593-b71c0d9a-3cd0-4bda-b666-ea618ebb92d3.png)

### ZED Camera model

ZED2

### Environment

```shell
OS: Windows10
GPU: NVidia 1080Ti
ZEDSDK: 3.7.0
CUDA: 10.2
Software: ZEDFu
```

### Anything else?

no

**Comment by alassagne-sl** [comment]
Hello,
Indeed it seems that the software fails to save the model.
- Can you make a screen recording of your exact process ? I'm not sure of what you do before pressing "reset", the reset button is not here in the beginning when you launch the app.
- Did you try with a shorter / longer recording time ?
- Do you have enough free space available ?
- Did you try to upgrade CUDA to 11.x ? that can only be better :)
