### ISSUE TITLE
XamlParseException - DllNotFoundException

### ISSUE THREAD

**Issue by LudoTexx** [stereolabs/zed-csharp-api#3]
Hey,

I have an issue with C# wrapper since i have fresh reformat my computer.

I have re-install in this order :

Visual studio 2019
Cuda 10.2 / 11
zed SDK 3.2.0

But when i try to use the dll, i got this error (runtime only, compilation ok) :
![zedError](https://user-images.githubusercontent.com/19667047/85274434-374f1f80-b47f-11ea-9749-9fcd2817dcd8.png)

My release output folder (with both zed dll) :

![zedError2](https://user-images.githubusercontent.com/19667047/85281877-0ecd2280-b48b-11ea-8b24-d8200cd47646.png)

Any idea? work fine on antoher computer with previous version SDK (3.1.2)

**Comment by obraun-sl** [comment]
Hi,
sl_zed_interface is not yet compatible with SDK 3.2.0. It will be soon compatible. 
In the meantime, please use the v3.1 SDK version.

**Comment by LudoTexx** [comment]
Ok, thank you, any realese date? We are in end of project.

Fast question, did the ZED sdk have an optic stabilisation option, lot of vibration on embed system (excavator)?

**Comment by obraun-sl** [comment]
Release Date : Before end of the week for sure. 
Optic Sabilisation : Not in the camera. You can use some rubber gimbal to reduce vibration

**Comment by LudoTexx** [comment]
Hello, any solution for working with  SDK 3.2.0?

**Comment by obraun-sl** [comment]
You can use the branch sdk_3.2 for compatibility with ZED SDK 3.2.0
https://github.com/stereolabs/zed-csharp-api/tree/sdk_3.2

**Comment by PrivHateVoid** [comment]
> You can use the branch sdk_3.2 for compatibility with ZED SDK 3.2.0
> https://github.com/stereolabs/zed-csharp-api/tree/sdk_3.2

Solved

**Comment by LudoTexx** [comment]
> You can use the branch sdk_3.2 for compatibility with ZED SDK 3.2.0
> https://github.com/stereolabs/zed-csharp-api/tree/sdk_3.2

Solved
