### ISSUE TITLE
Get detected objects distance

### ISSUE THREAD

**Issue by LudoTexx** [stereolabs/zed-csharp-api#7]
Hello,

Please could you tell me what the best way to get the position of an dtected object please?

I have try with ObjectDataSDK with : 

`obj.rootWorldPosition.Z `

but the returned value are really "unstable", and sometimes false (if too close).

I also tried that : 

```
                            distMat = new ZEDMat();

                            distMat.Create(res, MAT_TYPE.MAT_8U_C4, MEM.MEM_GPU);

                            camAR.RetrieveMeasure(distMat, MEASURE.DEPTH, MEM.MEM_GPU);
                            float depthCenter;

                            distMat.GetValue(960, 540, out depthCenter, MEM.MEM_GPU);
                            distMat.Free(MEM.MEM_GPU);
```

The accuracy seem better, (here i get the distance of the center of my image), but i'm not sure about how get the real distance of my object in my zone area, because of this :  (maybe write an algo for trying an average or something, but i prefere ask before loosing time for maybe nothing)

![CameraVue](https://user-images.githubusercontent.com/19667047/88173686-49111780-cc23-11ea-9aa9-8785a1f16ba5.PNG)

![CameraDessus](https://user-images.githubusercontent.com/19667047/88173684-48788100-cc23-11ea-86c5-9c72a891ad02.PNG)

Maybe all my try are totally false, but the value look good, the API doc do not match really with the C# API content.

Thank you in advance.

**Comment by LudoTexx** [comment]
Back from holidays.. no answer, bump please !

**Comment by obraun-sl** [comment]
Hi,
The obj.rootWorldPosition already gives (X,Y,Z) position of the root body, based on median value of points inside the bounding box. 
If you want to do something similar using the depth map, best will be to use the median value to avoid averaging outliers values.

**Comment by LudoTexx** [comment]
Yea, i have use that, is just weird if the object is too close, that do not return NaN, or null, but return a random value.
