### ISSUE TITLE
Should i add dll to reference on c#?

### ISSUE THREAD

**Issue by Wei10857104** [stereolabs/zed-csharp-api#9]
like c++ we need to add lib.
python we need to import pyzed.sl.

But how to use on c#, Should i need to add dll to reference on c#?
Then i can using what title to use these code.

InitParameters init_params = new InitParameters();
init_params.resolution = RESOLUTION.HD720;
init_params.cameraFPS = 60;
init_params.coordinateUnit = UNIT.METER;
init_params.coordinateSystem = COORDINATE_SYSTEM.RIGHT_HANDED_Y_UP;
init_params.depthMode = DEPTH_MODE.PERFORMANCE;

**Comment by Wei10857104** [comment]
my environment is visual c# 2017 and sdk3.10

enconter problem

![image](https://user-images.githubusercontent.com/69885789/90970278-765c2880-e535-11ea-9a03-25ec57361e93.png)

**Comment by Wei10857104** [comment]
![image](https://user-images.githubusercontent.com/69885789/90970288-8bd15280-e535-11ea-9a11-4b8f950f9811.png)

**Comment by obraun-sl** [comment]
You need to build the Stereolabs.zed in release and then right click on INSTALL >> generate. 
It will install the C interface + NET wrapper in C:/ProgramFiles(x86)/ZED SDK/bin
Make sure you have admin rights to do that.

**Comment by Lancename** [comment]
官方的工程有点小毛病.你把Image_Capture中引用里面的那个sl_zed_interface.dll移除，然后新添加stereolabs.zed.dll进去就可以

there is something wrong with the official project, and you remove the sl_zed_interface.dll referenced  in Image Capture,and then add stereolabs.zed.dll to it .  and it work well
